### ISSUE TITLE
hertz_server_latency_us_bucket面板上无数据

### ISSUE THREAD

**Issue by towelong** [hertz-contrib/monitor-prometheus#5]
`histogram_quantile(0.9,sum(rate(hertz_server_latency_us_bucket{statusCode="200"}[1m]))by(le))`
这条查询命令在面板上并无数据

**Comment by li-jin-gou** [comment]
确定一下点打上来了吗

**Comment by towelong** [comment]
> 确定一下点打上来了吗

![image](https://user-images.githubusercontent.com/41502558/222080585-a707a276-34c5-4789-aca1-7521d723beb5.png)
有的

**Comment by towelong** [comment]
![image](https://user-images.githubusercontent.com/41502558/222080704-c95bd2b5-16c1-4a86-90c9-0e57ce4955e8.png)
这个是有数据的

**Comment by Duslia** [comment]
用你的内网ip，不要写这个
<img width="666" alt="image" src="https://user-images.githubusercontent.com/37136584/222115972-5d87d3a6-0bb5-4c60-8325-bbc11161a218.png">

**Comment by towelong** [comment]
> 用你的内网ip，不要写这个 <img alt="image" width="666" src="https://user-images.githubusercontent.com/37136584/222115972-5d87d3a6-0bb5-4c60-8325-bbc11161a218.png">

ok

**Comment by towelong** [comment]
> 用你的内网ip，不要写这个 <img alt="image" width="666" src="https://user-images.githubusercontent.com/37136584/222115972-5d87d3a6-0bb5-4c60-8325-bbc11161a218.png">

不过我的9091是跟hertz服务跑在一起的，其它是在docker里面，这样的话我的networks要设置成host吗

**Comment by Duslia** [comment]
$inetIP 肯定访问不到啊。

**Comment by towelong** [comment]
> $inetIP 肯定访问不到啊。

得映射宿主机，我这边已经解决了，但是我感觉这个demo应该要改一改，我能提个PR吗？
因为这个demo跑起来还需要额外改下docker compose 文件才能完全跑通

**Comment by Duslia** [comment]
可以的～

**Comment by towelong** [comment]
> 可以的～

OK
